# ZAFİYETLİ: TLS yapılandırılmamış, 80 portu doğrudan HTTP servis ediyor
server {
    listen 80;
    server_name api.kargaa.com;

    location / {
        proxy_pass http://backend:4000;
        # TEHLİKE: Hassas Authorization başlıkları ağda plaintext akıyor
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
